services:

  mqtt:
    image: eclipse-mosquitto:2
    container_name: vdc-mqtt
    restart: unless-stopped

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

    networks:
      - vdc-network

  motor-simulator:
    build:
      context: ./core/simulator
    container_name: vdc-motor-01
    restart: unless-stopped
    depends_on:
      - mqtt

    networks:
      - vdc-network

networks:
  vdc-network:
    name: vdc-lab-network
    driver: bridge
