[agent]
  interval = "2s"
  flush_interval = "2s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt:1883"]
  topics = [
    "dc1/mechanical/motor/+/telemetry"
  ]

  data_format = "json"
  name_override = "motor_telemetry"

  tag_keys = [
    "device_id",
    "status"
  ]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
